###
GET http://localhost:3000/

###
GET http://localhost:3000/api/people

###
GET http://localhost:3000/api/people/18

###
POST http://localhost:3000/api/people
Content-Type: application/json

{
    "name": "The Mandalorian",
    "nickname": "Mando",
    "fav_color": "Dark",
    "location": "Mandalore",
    "bday": "unknown",
    "hobby1": 9,
    "hobby2": 4,
    "hobby3": 12
}

# Testing Delete
###
DELETE http://localhost:3000/api/people/27

# Testing Patch
###
PATCH http://localhost:3000/api/people/26
Content-Type: application/json

{
    "fav_color": "DARK",
    "location": "Star Wars"
}

###
PATCH http://localhost:3000/api/people/9
Content-Type: application/json

{
    "name":"The Mando"
}
